language: node_js
node_js: stable
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- npm run build
script:
- xvfb-run wct -l chrome
dist: trusty
sudo: required
